apiKey: "AIzaSyAEPz7_6yJJAAbWbdoXMMAzlZWTcs72w7k",
authDomain: "the-gamer-blog.firebaseapp.com",
databaseURL: "https://the-gamer-blog.firebaseio.com",
projectId: "the-gamer-blog",
storageBucket: "the-gamer-blog.appspot.com",
messagingSenderId: "180980062664",
appId: "1:180980062664:web:b5b97716c6b138eba508fd",
measurementId: "G-BB2R5VV5RJ"